lib/shipit/webhooks.rb
test/lib/shipit/wehbooks/handlers_test.rb

Fixes:
```
undefined method `each' for nil:NilClass
``` 
when receiving events for which there are no handlers registered: https://sentry.io/organizations/power-home-remodeling-group/issues/1403166986/?project=1833592&query=is%3Aunresolved

Unknown events have no handlers

---

app/controllers/shipit/repositories_controller.rb
app/models/shipit/repository.rb
app/views/shipit/repositories/settings.html.erb
db/migrate/20191231115348_add_per_pr_provisioning_opt_in_and_out_labels_to_repositories.rb
test/dummy/db/schema.rb

Allow repositories to configure per-Pull-Request auto-provisioning
behavior.
When "Dynamically provision stacks for Pull Requests" is enabled:
The "Allow All" (default) beahavior will provision a stack for every
pull request.
The "Allow With Label" behavior will provision a stack for a pull
request if, and only if, the pull request has a label matching the
value provided by the Repository's "Provisioning label" attribute.
The "Prevent With Label" behavior will provision stacks for all pull
requests EXCEPT those with a label matching the value provided by the
Repository's "Provisioning label" attribute.

Add ability to configure per-pull-request provisioning behavior

---

app/models/shipit/stack.rb
app/serializers/shipit/stack_serializer.rb
app/views/shipit/stacks/_banners.html.erb
db/migrate/20200115180018_add_lock_reason_code_to_stacks.rb
test/controllers/stacks_controller_test.rb
test/dummy/db/schema.rb
test/models/stacks_test.rb

This allows (efficiently) querying for stacks locked for this reason while retaining a user-friendly presentation.
Submitted separately upstream @ https://github.com/Shopify/shipit-engine/pull/991

Permit locking stacks with machine-readable reason

---

app/models/shipit/commit_deployment_status.rb
test/models/commit_deployment_status_test.rb

When creating a deployment status let's add the `environment_url` to
the payload we send to GitHub. The idea is that this gets us whatever
awesome features with which the GitHub API uses this value - automatic
linking to the deployment environment in the PR, etc.
References
----------
- https://developer.github.com/changes/2016-04-06-deployment-and-deployment-status-enhancements/#link-to-a-live-deployment

Add environment_url to deployment status events

---

app/views/shipit/stacks/_header.html.erb
app/views/shipit/stacks/_links.html.erb

Give the mounting application a way to define additional links which
apply to stacks across the system rather than per-stack.

Allow host application to define system-wide links to stack header

---

app/jobs/shipit/refresh_pull_request_job.rb
app/models/shipit/stack.rb
test/jobs/refresh_pull_request_job_test.rb

Require at least one GithubSyncJob has been successful for a stack
before refreshing its pull requests. When a pull requests is created
before stack sync it will create a detatched Shipit::Commit record for
its head ref. When GithubSyncJob runs afterward the
Sidekiq/Shipit::GithubSyncJob perpetually emits an
ActiveRecord::RecordNotUnique error becuase the GithubSyncJob attempts
to create the PullRequst's head ref Shipit::Commit again in a
non-detatched state and violates the index_commits_on_sha_and_stack_id
uniqueness index.

GithubSyncJob must run once before syncing pull requests

---

app/models/shipit/hook.rb
app/models/shipit/pull_request.rb
test/models/pull_request_test.rb

Allow pull request events to be emitted by the `Hook` class. Along with the `merge_status` events, the `pull_request` event is sent after every time a PR is saved.

[GOG-86] Introduces PR event and emits it after every changes

---

app/jobs/shipit/perform_task_job.rb
app/jobs/shipit/reap_dead_tasks_job.rb
app/models/shipit/stack.rb
app/models/shipit/task.rb
test/jobs/reap_dead_tasks_job_test.rb

There appears to be a race condition between the time when the
PerformTaskJob marks a task as "running" and when the newly added
RemoveDeadTasks job attempts to reap dead tasks.
In some cases a deployment is almost immediately marked as dead after
it starts. We believe this is because there critical section in which
PerformTaskJob marks a task as running and ReapDeadTaskJob is run in
which newly a task can be transitioned to a "running" status, but not
yet marked alive in which a newly created task will be considered a
"dead task" by the ReapDeaTasks job.
This changeset aims a two pronged approach at preventing this
race. First it makes the ReapDeadTasksJob less aggressive in its
consideration of tasks as "dead" - it will now only consider tasks in
a "running" or "aborted" state which are …

[GOG-153] Prevent erroneously marking deployments as dead soon after they start

---

app/models/shipit/stack.rb
test/models/stacks_test.rb

In 8c6ad042d768b2c743b6ca468c9ad0549a98e298 we accidentally changed
the return types of this method when bailing out early due to stack
readiness. Here we aim to restore the original "always nil" return
type.
References
----------
- https://github.com/powerhome/shipit-engine/commit/8c6ad042d768b2c743b6ca468c9ad0549a98e298
- https://ci.powerhrg.com/job/powerhome/job/milano/job/PR-283/5/console

Fix return type of Stack#trigger_continuous_delivery

---

app/models/shipit/pull_request.rb
app/models/shipit/pull_request_assignment.rb
app/models/shipit/user.rb
app/serializers/shipit/pull_request_serializer.rb
db/migrate/20200416194056_create_pull_request_assignments.rb
test/dummy/db/schema.rb
test/fixtures/shipit/pull_request_assignments.yml
test/models/pull_request_assignment_test.rb
test/models/pull_request_test.rb

Adds a relation between a pull request and a shipit user in order to track PR assignees.

[GOG-129] Adds pull request assignees to Ship It

---

app/models/shipit/stack.rb
db/migrate/20200518192351_add_provision_status_to_stacks.rb
test/dummy/db/schema.rb
test/models/shipit/stacks_provision_status_test.rb

In order to facilitate provisioning, provisioned-resource limits,
etc. for review stacks we want to introduce a proper "provisioning
status" to indicate the state of the Review Environment.
Note, this is a response to design feedback form the upstream
repository maintainers.
References
----------
- https://nitro.powerhrg.com/runway/backlog_items/GOG-179
- https://github.com/Shopify/shipit-engine/pull/991#issuecomment-575097398

Add provision_status state machine to review stacks

---

app/models/shipit/provisioning_handler.rb
app/models/shipit/provisioning_handler/base.rb
app/models/shipit/stack.rb
db/migrate/20200618021438_change_provision_status_default_to_deprovisioned.rb
test/dummy/db/schema.rb
test/jobs/perform_task_job_test.rb
test/models/shipit/stack_provisioning_handler_test.rb
test/models/shipit/stacks_provision_status_test.rb

In order to make the Review Stack concept more widely applicable, and
therefore ready for integration upstream, we want to make the
provisioning / deprovisioning of Review Stacks more general and
extensible.
The idea here is that the host application could supply its own
(de)provisioning routines - either per-repository, or as a global
default - which the stack will use when the appropriate transition
event occurs.
For example, imagine a repository which deploys to a Kubernetes
cluster. The host application could register a Kubernetes provisioning
handler to take care of creating / destroying kubernetes resources for
a stack:
- Define a provisioning Handler
```ruby
class KubernetesProvisioningHandler < Shipit::ProvisioningHandler::Base
def up
end
def down
end
end
```
- Register a default …

Expose provisioning lifecycle hooks

---

app/models/shipit/deploy_spec.rb
app/models/shipit/deploy_spec/file_system.rb
app/models/shipit/provisioning_handler.rb
app/models/shipit/provisioning_handler/unregistered_provisioning_handler.rb
app/models/shipit/stack.rb
docs/review_stacks.md
test/models/deploy_spec_test.rb
test/models/shipit/provisioning_handler/unregistered_provisioning_handler_test.rb
test/models/shipit/stack_provisioning_handler_test.rb

Notes
-----
Requires PR #35 to merge before this can be considered for adoption.
References
----------
- https://github.com/powerhome/shipit-engine/pull/35
- https://github.com/powerhome/shipit-engine/pull/35#issuecomment-648125441

Allow provisioning handler to be configured via shipit.yml

---

app/models/shipit/review_stack.rb
lib/tasks/cron.rake
test/controllers/stacks_controller_test.rb
test/fixtures/shipit/stacks.yml
test/models/shipit/review_stack_test.rb

Moves review stack cache and deployment directory cleanup out of Milano and to Shipit::ReviewStack

Implement cleanup routine

---

app/models/shipit/stack.rb
test/models/shipit/stacks_test.rb

We need to prevent deployments from happening for review stacks that are still in the queue waiting for resources to be provisioned.

Awaiting provision stacks should not be deployable

---

app/models/shipit/pull_request.rb
app/models/shipit/webhooks/handlers/pull_request/assigned_handler.rb
app/models/shipit/webhooks/handlers/pull_request/closed_handler.rb
app/models/shipit/webhooks/handlers/pull_request/edited_handler.rb
app/models/shipit/webhooks/handlers/pull_request/label_capturing_handler.rb
app/models/shipit/webhooks/handlers/pull_request/labeled_handler.rb
app/models/shipit/webhooks/handlers/pull_request/opened_handler.rb
app/models/shipit/webhooks/handlers/pull_request/reopened_handler.rb
app/models/shipit/webhooks/handlers/pull_request/review_stack_adapter.rb
app/models/shipit/webhooks/handlers/pull_request/unlabeled_handler.rb
app/serializers/shipit/pull_request_serializer.rb
db/migrate/20200823172649_add_head_reference_to_pull_requests.rb
test/dummy/db/schema.rb
test/fixtures/shipit/commits.yml
test/fixtures/shipit/pull_requests.yml
test/models/shipit/pull_request_test.rb
test/models/shipit/webhooks/handlers/pull_request/closed_handler_test.rb
test/models/shipit/webhooks/handlers/pull_request/label_capturing_handler_test.rb
test/models/shipit/webhooks/handlers/pull_request/labeled_handler_test.rb
test/models/shipit/webhooks/handlers/pull_request/opened_handler_test.rb
test/models/shipit/webhooks/handlers/pull_request/reopened_handler_test.rb
test/models/shipit/webhooks/handlers/pull_request/unlabeled_handler_test.rb
test/serializers/shipit/pull_request_serializer_test.rb

We use this in our host application to determine if the currenty
deployment would put the Review Stack in a "current with the head
of the pull request" state - if so, we send notifications to the user
who opened the pull request indicating that their instance is
"ready". This was missed in the original PullRequest implementation.

Add head commit to pull requests

---

app/models/shipit/pull_request.rb
app/models/shipit/webhooks/handlers/pull_request/assigned_handler.rb
app/models/shipit/webhooks/handlers/pull_request/closed_handler.rb
app/models/shipit/webhooks/handlers/pull_request/edited_handler.rb
app/models/shipit/webhooks/handlers/pull_request/label_capturing_handler.rb
app/models/shipit/webhooks/handlers/pull_request/labeled_handler.rb
app/models/shipit/webhooks/handlers/pull_request/opened_handler.rb
app/models/shipit/webhooks/handlers/pull_request/reopened_handler.rb
app/models/shipit/webhooks/handlers/pull_request/review_stack_adapter.rb
app/models/shipit/webhooks/handlers/pull_request/unlabeled_handler.rb
app/serializers/shipit/pull_request_serializer.rb
db/migrate/20200823172649_add_head_reference_to_pull_requests.rb
test/dummy/db/schema.rb
test/fixtures/shipit/commits.yml
test/fixtures/shipit/pull_requests.yml
test/models/shipit/pull_request_test.rb
test/models/shipit/webhooks/handlers/pull_request/closed_handler_test.rb
test/models/shipit/webhooks/handlers/pull_request/label_capturing_handler_test.rb
test/models/shipit/webhooks/handlers/pull_request/labeled_handler_test.rb
test/models/shipit/webhooks/handlers/pull_request/opened_handler_test.rb
test/models/shipit/webhooks/handlers/pull_request/reopened_handler_test.rb
test/models/shipit/webhooks/handlers/pull_request/unlabeled_handler_test.rb
test/serializers/shipit/pull_request_serializer_test.rb

Reverts powerhome/shipit-engine#62
Now that we're out of @benlangfeld 's way while diagnosing Milano, reinstate the "Capture head commit for pull requests" change set. We should probably wait to merge this until deployments are running smoothly again.
Also, wait until https://github.com/powerhome/nitro-web/pull/16642 lands in production as well.
Additionally, https://github.com/powerhome/milano/pull/444 will need to be updated to receive this once

Capture head commit for pull requsets

---

app/jobs/shipit/refresh_merge_request_job.rb
app/models/shipit/merge_request.rb
app/models/shipit/stack.rb
app/serializers/shipit/commit_serializer.rb
app/serializers/shipit/deploy_serializer.rb
app/serializers/shipit/merge_request_serializer.rb
app/serializers/shipit/stack_serializer.rb
app/views/shipit/stacks/index.html.erb
app/views/shipit/stacks/show.html.erb
lib/shipit/command.rb
test/controllers/api/rollback_controller_test.rb
test/jobs/perform_task_job_test.rb
test/jobs/refresh_merge_request_job_test.rb
test/models/merge_request_test.rb

Reverts powerhome/shipit-engine#65
This upstream merge was applied to the working branch as a squash commit. This essentially rewrites upstream history into a single commit and makes our working branch diverge into an un-mergable, conflicted state with the upstream. 
Instead, we plan to re-perform this operation as a proper merge of the upstream changes to retain compatible history.

Revert "Merge shopify master into pr review stacks branch"

---

app/models/shipit/stack.rb
app/views/shipit/stacks/_banners.html.erb
db/migrate/20200902103708_remove_stacks_lock_reason_code.rb
test/controllers/stacks_controller_test.rb
test/dummy/db/schema.rb
test/models/shipit/stacks_test.rb

This attribute is no longer used. We originally added this as a means indicate a ReviewStack's in/exclusion in the `Shipit::ReviewStackProvisioningQueue`. We've since removed this in favor of the `Stack#awaiting_provision` flag.

Remove stacks lock_reason_code

---

db/migrate/20191218185534_add_provision_pr_stacks_flag_to_repositories.rb
db/migrate/20200714210043_rename_provision_pr_stacks.rb

We _should_ create this feature toggle column with the appropriate
name from the beginning in the upstream PR.
Missed this one in 9d2ad939

Compress review stack feature flag migrations

---

app/models/shipit/webhooks/handlers/pull_request/review_stack_adapter.rb
test/models/shipit/webhooks/handlers/pull_request/opened_handler_test.rb

Last evening we observed a Review Stack was created without a Pull
Request. It is our intent that EVERY Review Stack should have an
associated Pull Request. We suspect that the call to
`PullRequest#update!` failed. Since creating the ReviewStack and
PullRequest are flushed to the database independently, we ended up
with a ReviewStack that was missing its PullRequest. This change
attempts to make the creation of the Review Stack and its Pull Request
atomic - ensuring that any Review Stack that is created will have
captured its Pull Request.

Atomically create Review Stacks and their Pull Requests

---

app/models/shipit/task_execution_strategy/default.rb

Adds some logs of the time it took to run every command during the deployment.

Logs time it took to run a command during a deployment

---

app/models/shipit/task_execution_strategy/default.rb

Using Time.now MAY be unreliable. On some systems, Time.now uses the
`gettimeofday` system call. The `gettimeofday` documentation states:
> The time returned by gettimeofday() is affected by discontinuous jumps
in the system time (e.g., if the system administrator manually changes
the system time).
IE this returns "wall time" of the system clock which MAY change
unexpectedly - for example if the system uses NTP to set time and the
clock adjusts during the execution of a task. Time.now is prone to
jumping around an inconsistent timeline.
Instead, this uses the system's monotonic clock to ensure that "time" is
consistently measured between the "start" and "stop" of a task.
References
----------
- http://man7.org/linux/man-pages/man2/gettimeofday.2.html
- …

Use the monotonic clock for task timing

---

lib/shipit/task_commands.rb

To prevent long-running git operations from being SIGINT-ed.

Make git operations noisy

---

lib/shipit/stack_commands.rb
lib/shipit/task_commands.rb
test/unit/deploy_commands_test.rb

The networking/disk performance incident which necessitated this extra logging to prevent  has since been resolved. We'd prefer to remove to remove the unnecessary logging if we no longer require it.
References
------------
- https://github.com/powerhome/shipit-engine/pull/81
- https://github.com/powerhome/shipit-engine/pull/82

Revert temporary workaround for poor data volume performance
